# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Birol/Desktop/Gym_Management_System_mxsoftware-master/assets/GUI/psiko_ekle.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(490, 417)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/olimpik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.kilo_edit = QtWidgets.QLineEdit(Form)
        self.kilo_edit.setObjectName("kilo_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kilo_edit)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.denge_edit = QtWidgets.QLineEdit(Form)
        self.denge_edit.setObjectName("denge_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.denge_edit)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.uzun_at_edit = QtWidgets.QLineEdit(Form)
        self.uzun_at_edit.setObjectName("uzun_at_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.uzun_at_edit)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.boy_edit = QtWidgets.QLineEdit(Form)
        self.boy_edit.setObjectName("boy_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.boy_edit)
        self.dikey_sic_edit = QtWidgets.QLineEdit(Form)
        self.dikey_sic_edit.setObjectName("dikey_sic_edit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dikey_sic_edit)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.esneklik_edit = QtWidgets.QLineEdit(Form)
        self.esneklik_edit.setObjectName("esneklik_edit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.esneklik_edit)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.kisametre_edit = QtWidgets.QLineEdit(Form)
        self.kisametre_edit.setObjectName("kisametre_edit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.kisametre_edit)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.uzun_metre_edit = QtWidgets.QLineEdit(Form)
        self.uzun_metre_edit.setObjectName("uzun_metre_edit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.uzun_metre_edit)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.tarih_edit = QtWidgets.QLineEdit(Form)
        self.tarih_edit.setObjectName("tarih_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tarih_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ekle_button = QtWidgets.QPushButton(Form)
        self.ekle_button.setObjectName("ekle_button")
        self.horizontalLayout.addWidget(self.ekle_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Psiko Ekle"))
        self.label.setText(_translate("Form", "Boy               :"))
        self.label_2.setText(_translate("Form", "Kilo                 :"))
        self.label_3.setText(_translate("Form", "Denge            :"))
        self.label_4.setText(_translate("Form", "Uzun Atlama   :"))
        self.label_5.setText(_translate("Form", "Dikey Sıçrama  :"))
        self.label_6.setText(_translate("Form", "Esneklik            :"))
        self.label_7.setText(_translate("Form", "30 Metre          :"))
        self.label_8.setText(_translate("Form", "100 Metre        :"))
        self.label_9.setText(_translate("Form", "Tarih              :"))
        self.tarih_edit.setPlaceholderText(_translate("Form", "30.08.2022 formatında Tarih girilmelidir"))
        self.ekle_button.setText(_translate("Form", "EKLE"))

import assets.py_rc.icons_rc as icons_rc
